create table if not exists public.group
(
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    group_id text null,
    group_name text null,
    active_mode boolean not null default false,
    constraint groupdb_pkey primary key (id)
) tablespace pg_default;

create table if not exists public.prompt
(
     id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    prompt_text text not null,
    group_fk bigint not null,
    token_size bigint not null,
    constraint promptdb_pkey primary key (id),
    constraint prompt_group_fk_fkey foreign key (group_fk) references "group" (id) on delete cascade
) tablespace pg_default;

create table if not exists public.message
(
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    prompt_fk bigint not null,
    message_type text null,
    message_Id text null,
    user_Id text null,
    user_name text null,
    phone text null,
    message text null,
    token_size bigint null,
    constraint messagedb_pkey primary key (id),
    constraint message_prompt_fk_fkey foreign key (prompt_fk) references prompt (id) on delete cascade
) tablespace pg_default;